### ISSUE TITLE
Convert Presenter to Draper (see Draper branch)

### ISSUE THREAD

**Issue by semia** [liftoff-team/sarce-trainer-admin#72]
Branche en cours : `draper`

**TODO**

- [x] Rebase on `master`
- [x] Extract methods from `QuestionPresenter`
- [x] Tests decorator's methods
- [x] Decorator `question` in controllers
- [x] Make us of decorator's methods in views
- [x] Remove Presenter folder

*A faire en binôme*

**Comment by arnlen** [comment]
Qui fait cette revue ?

**Comment by semia** [comment]
Est-ce bien nécessaire de faire une review ? Par contre il me semble qu'il n'y a jamais eu de PR mais je me trompe peut-être. Tu es celui qui a commité en dernier sur la branch draper. 
Je pense que c'est à toi de la merger directement dans master ? ou faire une Pr ?  :-)

**Comment by arnlen** [comment]
Ok, donc le travail n'est pas fini alors.
J'ai juste commencé le job avec @fabienalbi, mais il y a encore un peu de travail pour finir la conversion du Presenter vers le model Decorator.
Je repasse le ticket en TODO dans ce cas.
Merci ! :)
